# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetermineNextStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.DoneForNow", "types.GetOrderInformation", "types.DiscardSpam", "types.ProcessRefund", "types.RejectRefund", "types.RequestClarification", "types.EscalateTechnicalSupport", "types.RequestHumanApproval"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetermineNextStep", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.DoneForNow", "types.GetOrderInformation", "types.DiscardSpam", "types.ProcessRefund", "types.RejectRefund", "types.RequestClarification", "types.EscalateTechnicalSupport", "types.RequestHumanApproval"], __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetermineNextStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.DoneForNow", "stream_types.GetOrderInformation", "stream_types.DiscardSpam", "stream_types.ProcessRefund", "stream_types.RejectRefund", "stream_types.RequestClarification", "stream_types.EscalateTechnicalSupport", "stream_types.RequestHumanApproval"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetermineNextStep", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.DoneForNow", "stream_types.GetOrderInformation", "stream_types.DiscardSpam", "stream_types.ProcessRefund", "stream_types.RejectRefund", "stream_types.RequestClarification", "stream_types.EscalateTechnicalSupport", "stream_types.RequestHumanApproval"], __result__)

    