# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class DiscardSpam(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['discard_spam']] = Field(default=None, description='when the ticket is considered spam and need to be discarded.')

class DoneForNow(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['done']] = Field(default=None, description='when the ticket is processed.')

class EscalateTechnicalSupport(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['escalate_technical_support']] = None
    content: typing.Optional[str] = Field(default=None, description='a summary of the user\'s problem')
    user_email: typing.Optional[str] = None

class GetOrderInformation(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['get_order_information']] = None
    order_id: typing.Optional[str] = None

class ProcessRefund(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['process_refund']] = None
    order_id: typing.Optional[str] = None
    amount: typing.Optional[float] = None
    reason: typing.Optional[str] = None

class RejectRefund(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['reject_refund']] = None
    order_id: typing.Optional[str] = None
    reason: typing.Optional[str] = None

class RequestClarification(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['request_clarification']] = None
    reason: typing.Optional[str] = None

class RequestHumanApproval(BaseModel):
    intent: typing.Optional[typing_extensions.Literal['request_human_approval']] = None
    reason: typing.Optional[str] = None
    ticket_id: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (1)
# #########################################################################


Intent: typing_extensions.TypeAlias = typing.Optional[typing.Union["DoneForNow", "GetOrderInformation", "DiscardSpam", "ProcessRefund", "RejectRefund", "RequestClarification", "EscalateTechnicalSupport", "RequestHumanApproval"]]
