# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DiscardSpam": types.DiscardSpam,
    "stream_types.DiscardSpam": stream_types.DiscardSpam,

    "types.DoneForNow": types.DoneForNow,
    "stream_types.DoneForNow": stream_types.DoneForNow,

    "types.EscalateTechnicalSupport": types.EscalateTechnicalSupport,
    "stream_types.EscalateTechnicalSupport": stream_types.EscalateTechnicalSupport,

    "types.GetOrderInformation": types.GetOrderInformation,
    "stream_types.GetOrderInformation": stream_types.GetOrderInformation,

    "types.ProcessRefund": types.ProcessRefund,
    "stream_types.ProcessRefund": stream_types.ProcessRefund,

    "types.RejectRefund": types.RejectRefund,
    "stream_types.RejectRefund": stream_types.RejectRefund,

    "types.RequestClarification": types.RequestClarification,
    "stream_types.RequestClarification": stream_types.RequestClarification,

    "types.RequestHumanApproval": types.RequestHumanApproval,
    "stream_types.RequestHumanApproval": stream_types.RequestHumanApproval,


}