# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (8)
# #########################################################################

class DiscardSpam(BaseModel):
    intent: typing_extensions.Literal['discard_spam'] = Field(description='when the ticket is considered spam and need to be discarded.')

class DoneForNow(BaseModel):
    intent: typing_extensions.Literal['done'] = Field(description='when the ticket is processed.')

class EscalateTechnicalSupport(BaseModel):
    intent: typing_extensions.Literal['escalate_technical_support']
    content: str = Field(description='a summary of the user\'s problem')
    user_email: str

class GetOrderInformation(BaseModel):
    intent: typing_extensions.Literal['get_order_information']
    order_id: str

class ProcessRefund(BaseModel):
    intent: typing_extensions.Literal['process_refund']
    order_id: str
    amount: float
    reason: str

class RejectRefund(BaseModel):
    intent: typing_extensions.Literal['reject_refund']
    order_id: str
    reason: str

class RequestClarification(BaseModel):
    intent: typing_extensions.Literal['request_clarification']
    reason: str

class RequestHumanApproval(BaseModel):
    intent: typing_extensions.Literal['request_human_approval']
    reason: str
    ticket_id: str

# #########################################################################
# Generated type aliases (1)
# #########################################################################


Intent: typing_extensions.TypeAlias = typing.Union["DoneForNow", "GetOrderInformation", "DiscardSpam", "ProcessRefund", "RejectRefund", "RequestClarification", "EscalateTechnicalSupport", "RequestHumanApproval"]
